version: '3.8'

services:
  api:
    build: .
    container_name: api_escola_fastapi
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    